"""empty message

Revision ID: 15888f4c8eb1
Revises: f7ccab5ddf83
Create Date: 2024-06-10 10:39:56.172082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15888f4c8eb1'
down_revision = 'f7ccab5ddf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('_pasword_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_pasword_hash', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
